import sqlite3, time, sys
def log(m): print(m, flush=True)
log("=== stage 1a integrity_check start %s ===" % time.strftime("%H:%M:%S"))
t0=time.time()
db = sqlite3.connect('data/corpus.new.sqlite', timeout=600)
log("connected in %.1fs" % (time.time()-t0))
t1=time.time()
r = db.execute("PRAGMA integrity_check").fetchall()
log("integrity_check returned in %.1fs" % (time.time()-t1))
log("rows: %d" % len(r))
log("first 5: %s" % r[:5])
log("last 5: %s" % r[-5:])
ok = (len(r) == 1 and r[0][0] == "ok")
log("VERDICT: %s" % ("OK" if ok else "BROKEN"))
db.close()
log("=== stage 1a complete in %.1fs ===" % (time.time()-t0))
